spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myappdb
    username: myuser
    password: mysql@mysql123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Use 'validate' or 'none' in prod, 'update' is for dev convenience
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
